apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: nginx-ingress-lb
  name: nginx-ingress-controller
  namespace: default
spec:
  replicas: 1
  selector:
    k8s-app: nginx-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-lb
        name: nginx-ingress-lb
    spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --default-backend-service=default/nginx-errors
        - --nginx-configmap=default/nginx-template
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: aledbf/nginx-third-party:0.36
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: nginx-ingress-lb
        ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        - containerPort: 443
          hostPort: 4430
          protocol: TCP
        - containerPort: 8080
          hostPort: 8181
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/template
          name: nginx-template-volume
      - args:
        - /watch-resource-cmdrunner
        - --command=curl http://localhost:10254/reload-template
        - --file=/etc/nginx/template/nginx.tmpl
        - --container=nginx-ingress-lb
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: aledbf/watch-resource-cmdrunner:0.1
        imagePullPolicy: IfNotPresent
        name: watch-template
        volumeMounts:
        - mountPath: /etc/nginx/template
          name: nginx-template-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: nginx-template-volume
